name: Auto Changelog

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    if: "!startsWith(github.event.pull_request.title, 'release: v')"
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js 20.x for corepack
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ummgoban'

      - name: Enable Corepack and Set yarn Version
        run: |
          npm install -g corepack@latest
          corepack enable

      - name: Setup Node.js 20.x for yarn
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: yarn

      - name: Create .env
        run: |
          echo "NPM_TOKEN=${{ secrets.NPM_TOKEN }}" > .env

      - name: Install dependencies
        run: |
          sh .script/pre-install.sh
          yarn install

      - name: post-install
        run: sh .script/post-install.sh

      - name: Remove .env
        run: rm .env

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate changelog and bump version
        run: yarn release --skip.commit --skip.tag

      - name: Get new version
        id: get-version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'release: v${{ steps.get-version.outputs.VERSION }}'
          title: 'release: v${{ steps.get-version.outputs.VERSION }}'
          body: |
            이 PR은 자동으로 생성되었습니다.

            ## 변경 사항
            - package.json 버전 업데이트 (${{ steps.get-version.outputs.VERSION }})
            - CHANGELOG.md 갱신
          branch: auto-changelog-update
          base: main
          delete-branch: true
