name: Check

on:
  push:
    branches: ['*']
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.spec.ts'
      - '**/*.spec.tsx'
      - 'yarn.lock'

  pull_request:
    branches: ['*']
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.spec.ts'
      - '**/*.spec.tsx'
      - 'yarn.lock'
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run common checks
        id: pass
        uses: ./.github/actions/pass.yml

      - name: Check results
        if: steps.pass.outputs.all_pass != 'true'
        run: exit 1
