name: Create Release & Publish Package

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-release:
    # PR이 머지되었고 PR 제목이 'release: v'로 시작하는 경우에만 실행
    if: "github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'release: v')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from PR title
        id: extract-version
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          VERSION=$(echo $PR_TITLE | sed -n 's/release: v\(.*\)/\1/p')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Create and push tag
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          TAG_NAME="v${{ steps.extract-version.outputs.VERSION }}"
          echo "Creating tag: $TAG_NAME"

          git tag -a $TAG_NAME -m "Release $TAG_NAME"
          git push origin $TAG_NAME

      - name: Read CHANGELOG
        id: changelog
        run: |
          # CHANGELOG.md에서 현재 버전의 변경 사항을 추출
          VERSION="${{ steps.extract-version.outputs.VERSION }}"
          CHANGELOG_CONTENT=$(sed -n "/## \[${VERSION}\]/,/## \[/p" CHANGELOG.md | sed '$d')

          echo "CHANGELOG_CONTENT<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.extract-version.outputs.VERSION }}
          release_name: v${{ steps.extract-version.outputs.VERSION }}
          body: |
            ${{ steps.changelog.outputs.CHANGELOG_CONTENT }}
          draft: false
          prerelease: false
  publish:
    needs: create-release
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x for corepack
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@ummgoban'

      - name: Enable Corepack and Set yarn Version
        run: |
          npm install -g corepack@latest
          corepack enable

      - name: Setup Node.js 20.x for yarn
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Lint
        id: lint_check
        continue-on-error: true
        run: |
          yarn lint:check
          echo $? > lint_result

      - name: Format
        id: format_check
        continue-on-error: true
        run: |
          yarn format:check
          echo $? > format_result

      - name: Type Check
        id: type_check
        continue-on-error: true
        run: |
          yarn type-check
          echo $? > type_result

      - name: Test
        id: test_check
        continue-on-error: true
        run: |
          yarn test
          echo $? > test_result

      - name: Build
        id: build
        continue-on-error: true
        run: |
          yarn build
          echo $? > build_result

      - name: Check Lint & Format & Type Check & Test & Build Results
        id: check_results
        run: |
          if [ "$(cat lint_result)" -eq 0 ] && [ "$(cat format_result)" -eq 0 ] && [ "$(cat type_result)" -eq 0 ] && [ "$(cat test_result)" -eq 0 ] && [ "$(cat build_result)" -eq 0 ]; then
            echo "all_pass=true" >> $GITHUB_ENV
          else
            echo "all_pass=false" >> $GITHUB_ENV
          fi

      - name: Publish
        if: env.all_pass == 'true'
        run: yarn npm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
